"""Phase 2 join/identity validation for the HHGOA fraud dataset.

Re-checks, on demand, the specific factual claims Phase 2's dataset_inventory
and join_validation reports depend on:

  1. Every `case_pack.csv` `flagged_txn_id` exists in `transactions.csv` (TransactionID).
  2. Every `case_pack.csv` customer_id exists in `transactions.csv` customer_id.
  3. Every `closed_cases_history.csv` customer_id exists in `transactions.csv` customer_id.
  4. How many `transactions.csv` TransactionIDs have a matching `identity.csv` record.
  5. `customer_id` <-> `card1` is one-to-one in `transactions.csv`.
  6. `DeviceInfo` values (from identity.csv, joined to transactions.csv on
     TransactionID) shared across more than one customer_id.

This script only reads the columns it needs (never the full 397-column /
~708 MB `transactions.csv`) so it stays cheap to re-run whenever the data
changes. It does not touch V1-V339/C1-C14/D1-D15/M1-M9 — those are irrelevant
to join validation.

Usage:
    python -m data.validate_joins --data-dir data
    python -m data.validate_joins --data-dir data --write-report reports/join_validation.md

Exit code is non-zero if any hard invariant (checks 1, 2, 3, 5) fails.
Check 4 and 6 are informational (they describe the data; they don't "fail").
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd

# Columns actually needed for join validation, by file. Keeping this narrow
# is what makes it safe to re-run against the full transactions.csv.
TXN_ID_COL = "TransactionID"
CUSTOMER_COL = "customer_id"
CARD_COL = "card1"

TRANSACTIONS_COLS = [TXN_ID_COL, CUSTOMER_COL, CARD_COL]
IDENTITY_COLS = [TXN_ID_COL, "DeviceInfo"]
CASE_PACK_COLS = ["case_id", "flagged_txn_id", "customer_id"]
CLOSED_CASES_COLS = ["case_id", "customer_id"]


@dataclass
class CheckResult:
    name: str
    passed: bool
    detail: str
    metric: float | int | None = None
    informational: bool = False


@dataclass
class ValidationReport:
    results: list[CheckResult] = field(default_factory=list)

    def add(self, result: CheckResult) -> None:
        self.results.append(result)

    @property
    def hard_failures(self) -> list[CheckResult]:
        return [r for r in self.results if not r.informational and not r.passed]

    def to_markdown(self) -> str:
        lines = ["# Join Validation Results", "", "Generated by `src/data/validate_joins.py`.", ""]
        lines.append("| Check | Status | Detail |")
        lines.append("|---|---|---|")
        for r in self.results:
            status = "INFO" if r.informational else ("PASS" if r.passed else "FAIL")
            lines.append(f"| {r.name} | {status} | {r.detail} |")
        lines.append("")
        if self.hard_failures:
            lines.append(f"**{len(self.hard_failures)} hard invariant(s) failed.**")
        else:
            lines.append("All hard invariants passed.")
        return "\n".join(lines) + "\n"


def _read_csv(path: Path, usecols: list[str], dtype: type = str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Expected data file not found: {path}")
    return pd.read_csv(path, usecols=usecols, dtype=dtype, keep_default_na=False, na_values=[""])


def _clean_id_series(s: pd.Series) -> pd.Series:
    s = s.dropna().astype(str).str.strip()
    return s[s != ""]


# --------------------------------------------------------------------------
# Individual checks
# --------------------------------------------------------------------------


def check_benchmark_txn_ids_exist(case_pack: pd.DataFrame, transactions: pd.DataFrame) -> CheckResult:
    """Every case_pack.flagged_txn_id must exist as a transactions.TransactionID."""
    txn_ids = set(_clean_id_series(transactions[TXN_ID_COL]))
    flagged = _clean_id_series(case_pack["flagged_txn_id"])
    missing = sorted(set(flagged) - txn_ids)
    passed = len(missing) == 0
    detail = f"{len(flagged) - len(missing)}/{len(flagged)} benchmark flagged_txn_id values found in transactions.csv"
    if missing:
        detail += f"; missing: {missing[:10]}{' ...' if len(missing) > 10 else ''}"
    return CheckResult("benchmark_flagged_txn_id -> TransactionID", passed, detail, metric=len(missing))


def check_benchmark_customer_ids_exist(case_pack: pd.DataFrame, transactions: pd.DataFrame) -> CheckResult:
    """Every case_pack.customer_id must exist as a transactions.customer_id."""
    customer_ids = set(_clean_id_series(transactions[CUSTOMER_COL]))
    bench_customers = _clean_id_series(case_pack["customer_id"])
    missing = sorted(set(bench_customers) - customer_ids)
    passed = len(missing) == 0
    detail = (
        f"{len(bench_customers) - len(missing)}/{len(bench_customers)} benchmark customer_id values "
        f"found in transactions.csv"
    )
    if missing:
        detail += f"; missing: {missing[:10]}{' ...' if len(missing) > 10 else ''}"
    return CheckResult("benchmark customer_id -> transactions customer_id", passed, detail, metric=len(missing))


def check_closed_case_customer_ids_exist(closed_cases: pd.DataFrame, transactions: pd.DataFrame) -> CheckResult:
    """Every closed_cases_history.customer_id must exist as a transactions.customer_id."""
    customer_ids = set(_clean_id_series(transactions[CUSTOMER_COL]))
    closed_customers = _clean_id_series(closed_cases["customer_id"])
    missing = sorted(set(closed_customers) - customer_ids)
    passed = len(missing) == 0
    detail = (
        f"{len(closed_customers) - len(missing)}/{len(closed_customers)} closed-case customer_id values "
        f"found in transactions.csv"
    )
    if missing:
        detail += f"; missing: {missing[:10]}{' ...' if len(missing) > 10 else ''}"
    return CheckResult("closed_case customer_id -> transactions customer_id", passed, detail, metric=len(missing))


def check_identity_coverage(transactions: pd.DataFrame, identity: pd.DataFrame) -> CheckResult:
    """How many transactions have a matching identity.csv record (informational, not a pass/fail invariant).

    Coverage is expected to be partial and channel-dependent: identity.csv is
    "Online transactions only" per data/README.md, and in_person (ProductCD
    'W') transactions have no identity record by design. Low coverage is NOT
    a data-quality defect on its own.
    """
    txn_ids = _clean_id_series(transactions[TXN_ID_COL])
    identity_ids = set(_clean_id_series(identity[TXN_ID_COL]))
    matched = txn_ids.isin(identity_ids).sum()
    total = len(txn_ids)
    pct = round(100 * matched / total, 2) if total else 0.0
    detail = f"{matched}/{total} transactions ({pct}%) have a matching identity.csv record"
    return CheckResult("transaction -> identity TransactionID coverage", True, detail, metric=matched, informational=True)


def check_customer_card_one_to_one(transactions: pd.DataFrame) -> CheckResult:
    """customer_id <-> card1 must be one-to-one: each customer_id maps to exactly
    one card1 value, and each card1 value maps to exactly one customer_id.

    (This does NOT mean one customer has only one card overall — customers can
    hold several cards, e.g. C01234-K1, C01234-K2, in the case data. It means
    the specific `card1` Vesta column and `customer_id` do not cross-map in
    the transaction data: card1 behaves like a customer-level identifier in
    this dataset, not a distinct per-physical-card key.)
    """
    df = transactions[[CUSTOMER_COL, CARD_COL]].copy()
    df[CUSTOMER_COL] = df[CUSTOMER_COL].astype(str).str.strip()
    df[CARD_COL] = df[CARD_COL].astype(str).str.strip()
    df = df[(df[CUSTOMER_COL] != "") & (df[CARD_COL] != "")].drop_duplicates()

    cust_per_card = df.groupby(CARD_COL)[CUSTOMER_COL].nunique()
    card_per_cust = df.groupby(CUSTOMER_COL)[CARD_COL].nunique()

    bad_cards = cust_per_card[cust_per_card > 1]
    bad_customers = card_per_cust[card_per_cust > 1]

    passed = bad_cards.empty and bad_customers.empty
    n_customers = df[CUSTOMER_COL].nunique()
    n_cards = df[CARD_COL].nunique()
    detail = f"{n_customers} unique customer_id, {n_cards} unique card1, mapping is one-to-one"
    if not passed:
        detail = (
            f"NOT one-to-one: {len(bad_cards)} card1 value(s) map to >1 customer_id, "
            f"{len(bad_customers)} customer_id value(s) map to >1 card1 value"
        )
    return CheckResult("customer_id <-> card1 uniqueness", passed, detail, metric=n_customers)


def check_device_sharing(transactions: pd.DataFrame, identity: pd.DataFrame) -> CheckResult:
    """DeviceInfo values shared by more than one customer_id (informational — a
    shared device is an investigation signal per the project's own rules, not
    evidence of fraud on its own).
    """
    txn_small = transactions[[TXN_ID_COL, CUSTOMER_COL]].copy()
    joined = identity.merge(txn_small, on=TXN_ID_COL, how="inner")
    joined = joined[joined["DeviceInfo"].astype(str).str.strip() != ""]

    per_device = joined.groupby("DeviceInfo")[CUSTOMER_COL].nunique()
    n_devices = per_device.shape[0]
    shared = per_device[per_device > 1]
    max_customers = int(per_device.max()) if n_devices else 0

    detail = (
        f"{n_devices} unique DeviceInfo values; {len(shared)} shared by >1 customer_id; "
        f"max customers on one DeviceInfo value: {max_customers}"
    )
    return CheckResult("DeviceInfo shared-customer counts", True, detail, metric=len(shared), informational=True)


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------


def run_validation(data_dir: Path) -> ValidationReport:
    transactions = _read_csv(data_dir / "transactions.csv", TRANSACTIONS_COLS)
    identity = _read_csv(data_dir / "identity.csv", IDENTITY_COLS)
    case_pack = _read_csv(data_dir / "case_pack.csv", CASE_PACK_COLS)
    closed_cases = _read_csv(data_dir / "closed_cases_history.csv", CLOSED_CASES_COLS)

    report = ValidationReport()
    report.add(check_benchmark_txn_ids_exist(case_pack, transactions))
    report.add(check_benchmark_customer_ids_exist(case_pack, transactions))
    report.add(check_closed_case_customer_ids_exist(closed_cases, transactions))
    report.add(check_identity_coverage(transactions, identity))
    report.add(check_customer_card_one_to_one(transactions))
    report.add(check_device_sharing(transactions, identity))
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path("data"), help="Directory containing the 4 CSV files")
    parser.add_argument("--write-report", type=Path, default=None, help="Optional path to write a Markdown report")
    args = parser.parse_args(argv)

    report = run_validation(args.data_dir)

    for r in report.results:
        status = "INFO" if r.informational else ("PASS" if r.passed else "FAIL")
        print(f"[{status}] {r.name}: {r.detail}")

    if args.write_report:
        args.write_report.parent.mkdir(parents=True, exist_ok=True)
        args.write_report.write_text(report.to_markdown(), encoding="utf-8")
        print(f"\nReport written to {args.write_report}")

    if report.hard_failures:
        print(f"\n{len(report.hard_failures)} hard invariant(s) FAILED.")
        return 1
    print("\nAll hard invariants passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
